Add os.path.join simulator
This is an unreasonable error on one of the Windows 7 system.
It seems like a pirated Windows system, and have modified or incomplete
system files. That caused os.path.join not work.
I'm not sure, here is the log.

Exception in Tkinter callback
Traceback (most recent call last):
File "tkinter\__init__.py", line 1533, in __call__
File
"C:\Users\Public\tsktempVEI0KSZR\TskSetup\TskInstTheWizard\TskInstWizardM
odules\TskInstStepSetup.py", line 51, in <lambda>
command = lambda : Methods.StartInstall(window),
File
"C:\Users\Public\tsktempVEI0KSZR\TskSetup\TskInstTheWizard\TskInstWizardM
odules\TskInstStepSetup.py", line 31, in StartInstall
LibSetup.Wrapper_NewInstall()
File
"C:\Users\Public\tsktempVEI0KSZR\TskSetup\LibTskInst\LibTskInstSetup.py",
line 134, in Wrapper_NewInstall
Methods.CopyFiles.DoCopy()
File
"C:\Users\Public\tsktempVEI0KSZR\TskSetup\LibTskInst\LibTskInstSetup.py",
line 37, in DoCopy
Methods.CopyFiles.UnpackSWRSAddr()
File
"C:\Users\Public\tsktempVEI0KSZR\TskSetup\LibTskInst\LibTskInstSetup.py",
line 22, in UnpackSWRSAddr
archiveName = wizardCfg.UserData.SWRSAddr7z()
File
"C:\Users\Public\tsktempVEI0KSZR\TskSetup\LibTskInst\LibTskInstResources.
py", line 278, in SWRSAddr7z
return path.join(archiveSource, swrsaddr)
File "ntpath.py", line 110, in join
File "ntpath.py", line 159, in splitdrive
TypeError: object of type 'bool' has no len()